// <auto-generated/>
// Source: https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/common.py
// Run YtdlpPocoGenerator to regenerate this file.

#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace YtdlpPoco;

/// <summary>
/// A list of dictionaries, with the following entries:
/// This file is auto-generated by YtdlpPocoGenerator.
/// </summary>
public class ChapterData
{
    /// <summary>The start time of the chapter in seconds</summary>
    [JsonPropertyName("start_time")]
    public float? StartTime { get; set; }

    /// <summary>The end time of the chapter in seconds (optional: core code can determine this value from the next chapter's start_time or the video's duration)</summary>
    [JsonPropertyName("end_time")]
    public float? EndTime { get; set; }

    [JsonPropertyName("title")]
    public string? Title { get; set; }

}
