// <auto-generated/>
// Source: https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/common.py
// Run YtdlpPocoGenerator to regenerate this file.

#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace YtdlpPoco;

/// <summary>Represents a chapter within a video.</summary>
public class ChapterData
{
    /// <summary>Chapter start time in seconds.</summary>
    [JsonPropertyName("start_time")]
    public float? StartTime { get; set; }

    /// <summary>Chapter end time in seconds.</summary>
    [JsonPropertyName("end_time")]
    public float? EndTime { get; set; }

    /// <summary>Chapter title.</summary>
    [JsonPropertyName("title")]
    public string? Title { get; set; }

}
