// <auto-generated/>
// Source: https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/common.py
// Run YtdlpPocoGenerator to regenerate this file.

#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace YtdlpPoco;

/// <summary>Represents a comment on a video.</summary>
public class CommentData
{
    /// <summary>Comment identifier.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>Comment text.</summary>
    [JsonPropertyName("text")]
    public string? Text { get; set; }

    /// <summary>Comment author name.</summary>
    [JsonPropertyName("author")]
    public string? Author { get; set; }

    /// <summary>Comment author identifier.</summary>
    [JsonPropertyName("author_id")]
    public string? AuthorId { get; set; }

    /// <summary>URL to the comment author's profile.</summary>
    [JsonPropertyName("author_url")]
    public string? AuthorUrl { get; set; }

    /// <summary>URL to the author's thumbnail.</summary>
    [JsonPropertyName("author_thumbnail")]
    public string? AuthorThumbnail { get; set; }

    /// <summary>Parent comment ID for replies.</summary>
    [JsonPropertyName("parent")]
    public string? Parent { get; set; }

    /// <summary>UNIX timestamp of the comment.</summary>
    [JsonPropertyName("timestamp")]
    public long? Timestamp { get; set; }

    /// <summary>Number of likes on the comment.</summary>
    [JsonPropertyName("like_count")]
    public long? LikeCount { get; set; }

    /// <summary>Number of dislikes on the comment.</summary>
    [JsonPropertyName("dislike_count")]
    public long? DislikeCount { get; set; }

    /// <summary>Whether the comment is favorited by the uploader.</summary>
    [JsonPropertyName("is_favorited")]
    public bool? IsFavorited { get; set; }

    /// <summary>Whether the commenter is the video uploader.</summary>
    [JsonPropertyName("author_is_uploader")]
    public bool? AuthorIsUploader { get; set; }

}
