// <auto-generated/>
// Source: https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/common.py
// Run YtdlpPocoGenerator to regenerate this file.

#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace YtdlpPoco;

/// <summary>
/// A list of comments, each with one or more of the following properties (all but one of text or html optional):
/// This file is auto-generated by YtdlpPocoGenerator.
/// </summary>
public class CommentData
{
    /// <summary>human-readable name of the comment author</summary>
    [JsonPropertyName("author")]
    public string? Author { get; set; }

    /// <summary>user ID of the comment author</summary>
    [JsonPropertyName("author_id")]
    public string? AuthorId { get; set; }

    /// <summary>The thumbnail of the comment author</summary>
    [JsonPropertyName("author_thumbnail")]
    public string? AuthorThumbnail { get; set; }

    /// <summary>The url to the comment author's page</summary>
    [JsonPropertyName("author_url")]
    public string? AuthorUrl { get; set; }

    /// <summary>Whether the author is verified on the platform</summary>
    [JsonPropertyName("author_is_verified")]
    public bool? AuthorIsVerified { get; set; }

    /// <summary>Whether the comment is made by the video uploader</summary>
    [JsonPropertyName("author_is_uploader")]
    public bool? AuthorIsUploader { get; set; }

    /// <summary>Comment ID</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>Comment as HTML</summary>
    [JsonPropertyName("html")]
    public string? Html { get; set; }

    /// <summary>Plain text of the comment</summary>
    [JsonPropertyName("text")]
    public string? Text { get; set; }

    /// <summary>UNIX timestamp of comment</summary>
    [JsonPropertyName("timestamp")]
    public long? Timestamp { get; set; }

    /// <summary>ID of the comment this one is replying to.</summary>
    [JsonPropertyName("parent")]
    public string? Parent { get; set; }

    /// <summary>Number of positive ratings of the comment</summary>
    [JsonPropertyName("like_count")]
    public long? LikeCount { get; set; }

    /// <summary>Number of negative ratings of the comment</summary>
    [JsonPropertyName("dislike_count")]
    public long? DislikeCount { get; set; }

    /// <summary>Whether the comment is marked as favorite by the video uploader</summary>
    [JsonPropertyName("is_favorited")]
    public bool? IsFavorited { get; set; }

    /// <summary>Whether the comment is pinned to the top of the comments</summary>
    [JsonPropertyName("is_pinned")]
    public bool? IsPinned { get; set; }

}
