// <auto-generated/>
// Source: https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/common.py
// Run YtdlpPocoGenerator to regenerate this file.

#nullable enable

using System.Text.Json.Serialization;

namespace YtdlpPoco;

/// <summary>Under what condition the video is available.</summary>
public enum Availability
{
    [JsonStringEnumMemberName("private")]
    Private,

    [JsonStringEnumMemberName("premium_only")]
    PremiumOnly,

    [JsonStringEnumMemberName("subscriber_only")]
    SubscriberOnly,

    [JsonStringEnumMemberName("needs_auth")]
    NeedsAuth,

    [JsonStringEnumMemberName("unlisted")]
    Unlisted,

    [JsonStringEnumMemberName("public")]
    Public,

}

/// <summary>The dynamic range of the video.</summary>
public enum DynamicRange
{
    [JsonStringEnumMemberName("SDR")]
    SDR,

    [JsonStringEnumMemberName("HDR10")]
    HDR10,

    [JsonStringEnumMemberName("HDR12")]
    HDR12,

    [JsonStringEnumMemberName("DV")]
    DV,

}

/// <summary>None (=unknown), 'is_live', 'is_upcoming', 'was_live', 'not_live', or 'post_live' (was live, but VOD is not yet processed) If absent, automatically set from is_live, was_live</summary>
public enum LiveStatus
{
    [JsonStringEnumMemberName("is_live")]
    IsLive,

    [JsonStringEnumMemberName("is_upcoming")]
    IsUpcoming,

    [JsonStringEnumMemberName("was_live")]
    WasLive,

    [JsonStringEnumMemberName("not_live")]
    NotLive,

    [JsonStringEnumMemberName("post_live")]
    PostLive,

}

/// <summary>The protocol that will be used for the actual download, lower-case.</summary>
public enum Protocol
{
    [JsonStringEnumMemberName("http")]
    Http,

    [JsonStringEnumMemberName("https")]
    Https,

}

