// <auto-generated/>
// Source: https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/common.py
// Run YtdlpPocoGenerator to regenerate this file.

#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace YtdlpPoco;

/// <summary>
/// A list of dictionaries for each format available, ordered from worst to best quality.
/// This file is auto-generated by YtdlpPocoGenerator.
/// </summary>
public class FormatData
{
    /// <summary>The mandatory URL representing the media: for plain file media - HTTP URL of this file, for RTMP - RTMP URL, for HLS - URL of the M3U8 media playlist, for HDS - URL of the F4M manifest, for DASH - HTT…</summary>
    [JsonPropertyName("url")]
    public string? Url { get; set; }

    /// <summary>Data to send in POST request to the URL</summary>
    [JsonPropertyName("request_data")]
    public string? RequestData { get; set; }

    /// <summary>The URL of the manifest file in case of fragmented media: for HLS - URL of the M3U8 master playlist, for HDS - URL of the F4M manifest, for DASH - URL of the MPD manifest, for MSS - URL of the ISM man…</summary>
    [JsonPropertyName("manifest_url")]
    public string? ManifestUrl { get; set; }

    /// <summary>The index of the stream in the manifest file</summary>
    [JsonPropertyName("manifest_stream_number")]
    public long? ManifestStreamNumber { get; set; }

    /// <summary>Will be calculated from URL if missing</summary>
    [JsonPropertyName("ext")]
    public string? Ext { get; set; }

    /// <summary>A human-readable description of the format (&quot;mp4 container with h264/opus&quot;).</summary>
    [JsonPropertyName("format")]
    public string? Format { get; set; }

    /// <summary>A short description of the format (&quot;mp4_h264_opus&quot; or &quot;19&quot;).</summary>
    [JsonPropertyName("format_id")]
    public string? FormatId { get; set; }

    /// <summary>Additional info about the format (&quot;3D&quot; or &quot;DASH video&quot;)</summary>
    [JsonPropertyName("format_note")]
    public string? FormatNote { get; set; }

    /// <summary>Width of the video, if known</summary>
    [JsonPropertyName("width")]
    public string? Width { get; set; }

    /// <summary>Height of the video, if known</summary>
    [JsonPropertyName("height")]
    public string? Height { get; set; }

    /// <summary>Aspect ratio of the video, if known Automatically calculated from width and height</summary>
    [JsonPropertyName("aspect_ratio")]
    public string? AspectRatio { get; set; }

    /// <summary>Textual description of width and height Automatically calculated from width and height</summary>
    [JsonPropertyName("resolution")]
    public string? Resolution { get; set; }

    /// <summary>The dynamic range of the video.</summary>
    [JsonConverter(typeof(JsonStringEnumConverter<DynamicRange>))]
    [JsonPropertyName("dynamic_range")]
    public DynamicRange? DynamicRange { get; set; }

    /// <summary>Average bitrate of audio and video in kbps (1000 bits/sec)</summary>
    [JsonPropertyName("tbr")]
    public double? Tbr { get; set; }

    /// <summary>Average audio bitrate in kbps (1000 bits/sec)</summary>
    [JsonPropertyName("abr")]
    public double? Abr { get; set; }

    /// <summary>Name of the audio codec in use</summary>
    [JsonPropertyName("acodec")]
    public string? Acodec { get; set; }

    /// <summary>Audio sampling rate in Hertz</summary>
    [JsonPropertyName("asr")]
    public string? Asr { get; set; }

    /// <summary>Number of audio channels</summary>
    [JsonPropertyName("audio_channels")]
    public long? AudioChannels { get; set; }

    /// <summary>Average video bitrate in kbps (1000 bits/sec)</summary>
    [JsonPropertyName("vbr")]
    public double? Vbr { get; set; }

    /// <summary>Frame rate</summary>
    [JsonPropertyName("fps")]
    public string? Fps { get; set; }

    /// <summary>Name of the video codec in use</summary>
    [JsonPropertyName("vcodec")]
    public string? Vcodec { get; set; }

    /// <summary>Name of the container format</summary>
    [JsonPropertyName("container")]
    public string? Container { get; set; }

    /// <summary>The number of bytes, if known in advance</summary>
    [JsonPropertyName("filesize")]
    public long? Filesize { get; set; }

    /// <summary>An estimate for the number of bytes</summary>
    [JsonPropertyName("filesize_approx")]
    public long? FilesizeApprox { get; set; }

    /// <summary>SWF Player URL (used for rtmpdump).</summary>
    [JsonPropertyName("player_url")]
    public string? PlayerUrl { get; set; }

    /// <summary>The protocol that will be used for the actual download, lower-case.</summary>
    [JsonConverter(typeof(JsonStringEnumConverter<Protocol>))]
    [JsonPropertyName("protocol")]
    public Protocol? Protocol { get; set; }

    /// <summary>Base URL for fragments.</summary>
    [JsonPropertyName("fragment_base_url")]
    public string? FragmentBaseUrl { get; set; }

    /// <summary>A list of fragments of a fragmented media.</summary>
    [JsonPropertyName("fragments")]
    public string[]? Fragments { get; set; }

    /// <summary>fragment's path relative to fragment_base_url</summary>
    [JsonPropertyName("path")]
    public string? Path { get; set; }

    [JsonPropertyName("duration")]
    public string? Duration { get; set; }

    /// <summary>The M3U8 media playlist data as a string.</summary>
    [JsonPropertyName("hls_media_playlist_data")]
    public string? HlsMediaPlaylistData { get; set; }

    /// <summary>Is a live format that can be downloaded from the start.</summary>
    [JsonPropertyName("is_from_start")]
    public bool? IsFromStart { get; set; }

    /// <summary>Order number of this format.</summary>
    [JsonPropertyName("preference")]
    public long? Preference { get; set; }

    /// <summary>Language code, e.</summary>
    [JsonPropertyName("language")]
    public string? Language { get; set; }

    /// <summary>Is this in the language mentioned in the URL? 10 if it's what the URL is about, -1 for default (don't know), -10 otherwise, other values reserved for now.</summary>
    [JsonPropertyName("language_preference")]
    public string? LanguagePreference { get; set; }

    /// <summary>Order number of the video quality of this format, irrespective of the file format.</summary>
    [JsonPropertyName("quality")]
    public long? Quality { get; set; }

    /// <summary>Order number for this video source (quality takes higher priority) -1 for default (order by other properties), -2 or smaller for less than default.</summary>
    [JsonPropertyName("source_preference")]
    public string? SourcePreference { get; set; }

    /// <summary>A dictionary of additional HTTP headers to add to the request.</summary>
    [JsonPropertyName("http_headers")]
    public Dictionary<string, object[]>? HttpHeaders { get; set; }

    /// <summary>If given and not 1, indicates that the video's pixels are not square.</summary>
    [JsonPropertyName("stretched_ratio")]
    public string? StretchedRatio { get; set; }

    /// <summary>The server does not support resuming the (HTTP or RTMP) download.</summary>
    [JsonPropertyName("no_resume")]
    public bool? NoResume { get; set; }

    /// <summary>True if the format has DRM and cannot be downloaded.</summary>
    [JsonPropertyName("has_drm")]
    public bool? HasDrm { get; set; }

    /// <summary>A query string to append to each fragment's URL, or to update each existing query string with.</summary>
    [JsonPropertyName("extra_param_to_segment_url")]
    public string? ExtraParamToSegmentUrl { get; set; }

    /// <summary>A query string to append to the URL of the format's HLS AES-128 decryption key.</summary>
    [JsonPropertyName("extra_param_to_key_url")]
    public string? ExtraParamToKeyUrl { get; set; }

    /// <summary>A dictionary of HLS AES-128 decryption information used by the native HLS downloader to override the values in the media playlist when an '#EXT-X-KEY' tag is present in the playlist:</summary>
    [JsonPropertyName("hls_aes")]
    public Dictionary<string, object[]>? HlsAes { get; set; }

    /// <summary>The URI from which the key will be downloaded</summary>
    [JsonPropertyName("uri")]
    public string? Uri { get; set; }

    /// <summary>The key (as hex) used to decrypt fragments.</summary>
    [JsonPropertyName("key")]
    public string? Key { get; set; }

    /// <summary>The IV (as hex) used to decrypt fragments</summary>
    [JsonPropertyName("iv")]
    public string? Iv { get; set; }

    /// <summary>Impersonate target(s).</summary>
    [JsonPropertyName("impersonate")]
    public string? Impersonate { get; set; }

    /// <summary>instance of yt_dlp.</summary>
    [JsonPropertyName("an")]
    public string? An { get; set; }

    /// <summary>string in the format of CLIENT[:OS]</summary>
    [JsonPropertyName("a")]
    public string? A { get; set; }

    /// <summary>Unix timestamp of when a format will be available to download</summary>
    [JsonPropertyName("available_at")]
    public long? AvailableAt { get; set; }

    /// <summary>A dictionary of downloader options (For internal use only)</summary>
    [JsonPropertyName("downloader_options")]
    public Dictionary<string, object[]>? DownloaderOptions { get; set; }

    /// <summary>Chunk size for HTTP downloads</summary>
    [JsonPropertyName("http_chunk_size")]
    public string? HttpChunkSize { get; set; }

    /// <summary>Extra arguments for ffmpeg downloader (input)</summary>
    [JsonPropertyName("ffmpeg_args")]
    public string? FfmpegArgs { get; set; }

    /// <summary>Extra arguments for ffmpeg downloader (output)</summary>
    [JsonPropertyName("ffmpeg_args_out")]
    public string? FfmpegArgsOut { get; set; }

    /// <summary>WebSocketResponse</summary>
    [JsonPropertyName("ws")]
    public string? Ws { get; set; }

    /// <summary>Websockets URL</summary>
    [JsonPropertyName("ws_url")]
    public string? WsUrl { get; set; }

    /// <summary>Max stream quality string</summary>
    [JsonPropertyName("max_quality")]
    public string? MaxQuality { get; set; }

    /// <summary>Whether the format is a result of merging multiple DASH periods.</summary>
    [JsonPropertyName("is_dash_periods")]
    public bool? IsDashPeriods { get; set; }

}
