// <auto-generated/>
// Source: https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/common.py
// Run YtdlpPocoGenerator to regenerate this file.

#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace YtdlpPoco;

/// <summary>
/// A list of dictionaries, with the following entries:
/// This file is auto-generated by YtdlpPocoGenerator.
/// </summary>
public class HeatmapData
{
    /// <summary>The start time of the data point in seconds</summary>
    [JsonPropertyName("start_time")]
    public float? StartTime { get; set; }

    /// <summary>The end time of the data point in seconds</summary>
    [JsonPropertyName("end_time")]
    public float? EndTime { get; set; }

    /// <summary>The normalized value of the data point (float between 0 and 1)</summary>
    [JsonPropertyName("value")]
    public string? Value { get; set; }

}
