// <auto-generated/>
// Source: https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/common.py
// Run YtdlpPocoGenerator to regenerate this file.

#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace YtdlpPoco;

/// <summary>Represents one subtitle format for a given language.</summary>
public class SubtitleData
{
    /// <summary>Subtitle file extension.</summary>
    [JsonPropertyName("ext")]
    public string? Ext { get; set; }

    /// <summary>URL to the subtitle file.</summary>
    [JsonPropertyName("url")]
    public string? Url { get; set; }

    /// <summary>Inline subtitle data.</summary>
    [JsonPropertyName("data")]
    public string? Data { get; set; }

    /// <summary>Human-readable subtitle format name.</summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }

}
