// <auto-generated/>
// Source: https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/common.py
// Run YtdlpPocoGenerator to regenerate this file.

#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace YtdlpPoco;

/// <summary>
/// The available subtitles as a dictionary in the format {tag: subformats}.
/// This file is auto-generated by YtdlpPocoGenerator.
/// </summary>
public class SubtitleData
{
    /// <summary>The subtitles file contents</summary>
    [JsonPropertyName("data")]
    public string? Data { get; set; }

    /// <summary>A URL pointing to the subtitles file It can optionally also have:</summary>
    [JsonPropertyName("url")]
    public string? Url { get; set; }

    /// <summary>Name or description of the subtitles</summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <summary>A dictionary of additional HTTP headers to add to the request.</summary>
    [JsonPropertyName("http_headers")]
    public Dictionary<string, object[]>? HttpHeaders { get; set; }

    /// <summary>Impersonate target(s); same as the &quot;formats&quot; field &quot;ext&quot; will be calculated from URL if missing</summary>
    [JsonPropertyName("impersonate")]
    public string? Impersonate { get; set; }

}
