// <auto-generated/>
// Source: https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/common.py
// Run YtdlpPocoGenerator to regenerate this file.

#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace YtdlpPoco;

/// <summary>Represents a thumbnail image for a video.</summary>
public class ThumbnailData
{
    /// <summary>Thumbnail format ID.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>URL of the thumbnail.</summary>
    [JsonPropertyName("url")]
    public string? Url { get; set; }

    /// <summary>Quality preference of the thumbnail.</summary>
    [JsonPropertyName("preference")]
    public int? Preference { get; set; }

    /// <summary>Thumbnail width in pixels.</summary>
    [JsonPropertyName("width")]
    public int? Width { get; set; }

    /// <summary>Thumbnail height in pixels.</summary>
    [JsonPropertyName("height")]
    public int? Height { get; set; }

    /// <summary>Resolution string (e.g. 1920x1080).</summary>
    [JsonPropertyName("resolution")]
    public string? Resolution { get; set; }

    /// <summary>Thumbnail file size in bytes.</summary>
    [JsonPropertyName("filesize")]
    public long? Filesize { get; set; }

}
