// <auto-generated/>
// Source: https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/common.py
// Run YtdlpPocoGenerator to regenerate this file.

#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace YtdlpPoco;

/// <summary>
/// A list of dictionaries, with the following entries:
/// This file is auto-generated by YtdlpPocoGenerator.
/// </summary>
public class ThumbnailData
{
    /// <summary>Thumbnail format ID</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    [JsonPropertyName("url")]
    public string? Url { get; set; }

    /// <summary>actual image extension if not given in URL</summary>
    [JsonPropertyName("ext")]
    public string? Ext { get; set; }

    /// <summary>quality of the image</summary>
    [JsonPropertyName("preference")]
    public int? Preference { get; set; }

    [JsonPropertyName("width")]
    public int? Width { get; set; }

    [JsonPropertyName("height")]
    public int? Height { get; set; }

    /// <summary>(optional, string &quot;{width}x{height}&quot;,</summary>
    [JsonPropertyName("resolution")]
    public string? Resolution { get; set; }

    [JsonPropertyName("filesize")]
    public int? Filesize { get; set; }

    /// <summary>HTTP headers for the request</summary>
    [JsonPropertyName("http_headers")]
    public string? HttpHeaders { get; set; }

}
