// <auto-generated/>
// Source: https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/common.py
// Run YtdlpPocoGenerator to regenerate this file.

#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace YtdlpPoco;

/// <summary>
/// Represents video metadata as extracted by yt-dlp.
/// See <see href="https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/common.py">yt-dlp common.py</see> for field documentation.
/// This file is auto-generated by YtdlpPocoGenerator.
/// </summary>
public class VideoData
{
    /// <summary>The result type: video, playlist, url, etc.</summary>
    [JsonPropertyName("_type")]
    public string? ResultType { get; set; }

    /// <summary>Video identifier.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>Video title, unescaped. Set to an empty string if video has no title as opposed to &quot;None&quot; which signifies that the extractor failed to obtain a title</summary>
    [JsonPropertyName("title")]
    public string? Title { get; set; }

    /// <summary>A list of dictionaries for each format available, ordered from worst to best quality. Potential fields: * url        The mandatory URL representing the media: for plain file media - HTTP URL of this file, for RTMP - RTMP URL, for HLS - URL of the M3U8 media playlist, for HDS - URL of the F4M manifest, for DASH - HTTP URL to plain file media (in case of unfragmented media) - URL of the MPD manifest or base URL representing the media if MPD manifest is parsed from a string (in case of fragmented media) for MSS - URL of the ISM manifest. * request_data  Data to send in POST request to the URL</summary>
    [JsonPropertyName("formats")]
    public FormatData[]? Formats { get; set; }

    /// <summary>Final video URL.</summary>
    [JsonPropertyName("url")]
    public string? Url { get; set; }

    /// <summary>Video filename extension.</summary>
    [JsonPropertyName("ext")]
    public string? Ext { get; set; }

    /// <summary>The video format, defaults to ext (used for --get-format)</summary>
    [JsonPropertyName("format")]
    public string? Format { get; set; }

    /// <summary>SWF Player URL (used for rtmpdump).</summary>
    [JsonPropertyName("player_url")]
    public string? PlayerUrl { get; set; }

    /// <summary>True if a direct video file was given (must only be set by GenericIE)</summary>
    [JsonPropertyName("direct")]
    public bool? Direct { get; set; }

    /// <summary>A secondary title of the video.</summary>
    [JsonPropertyName("alt_title")]
    public string? AltTitle { get; set; }

    /// <summary>An alternative identifier for the video, not necessarily unique, but available before title. Typically, id is something like &quot;4234987&quot;, title &quot;Dancing naked mole rats&quot;, and display_id &quot;dancing-naked-mole-rats&quot;</summary>
    [JsonPropertyName("display_id")]
    public string? DisplayId { get; set; }

    /// <summary>A list of dictionaries, with the following entries:</summary>
    [JsonPropertyName("thumbnails")]
    public ThumbnailData[]? Thumbnails { get; set; }

    /// <summary>Full URL to a video thumbnail image.</summary>
    [JsonPropertyName("thumbnail")]
    public string? Thumbnail { get; set; }

    /// <summary>Full video description.</summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }

    /// <summary>Full name of the video uploader.</summary>
    [JsonPropertyName("uploader")]
    public string? Uploader { get; set; }

    /// <summary>License name the video is licensed under.</summary>
    [JsonPropertyName("license")]
    public string? License { get; set; }

    /// <summary>List of creators of the video.</summary>
    [JsonPropertyName("creators")]
    public string[]? Creators { get; set; }

    /// <summary>UNIX timestamp of the moment the video was uploaded</summary>
    [JsonPropertyName("timestamp")]
    public long? Timestamp { get; set; }

    /// <summary>Video upload date in UTC (YYYYMMDD). If not explicitly set, calculated from timestamp</summary>
    [JsonPropertyName("upload_date")]
    public string? UploadDate { get; set; }

    /// <summary>UNIX timestamp of the moment the video was released. If it is not clear whether to use timestamp or this, use the former</summary>
    [JsonPropertyName("release_timestamp")]
    public long? ReleaseTimestamp { get; set; }

    /// <summary>The date (YYYYMMDD) when the video was released in UTC. If not explicitly set, calculated from release_timestamp</summary>
    [JsonPropertyName("release_date")]
    public string? ReleaseDate { get; set; }

    /// <summary>Year (YYYY) as integer when the video or album was released. To be used if no exact release date is known. If not explicitly set, calculated from release_date.</summary>
    [JsonPropertyName("release_year")]
    public int? ReleaseYear { get; set; }

    /// <summary>UNIX timestamp of the moment the video was last modified.</summary>
    [JsonPropertyName("modified_timestamp")]
    public long? ModifiedTimestamp { get; set; }

    /// <summary>The date (YYYYMMDD) when the video was last modified in UTC. If not explicitly set, calculated from modified_timestamp</summary>
    [JsonPropertyName("modified_date")]
    public string? ModifiedDate { get; set; }

    /// <summary>Nickname or id of the video uploader.</summary>
    [JsonPropertyName("uploader_id")]
    public string? UploaderId { get; set; }

    /// <summary>Full URL to a personal webpage of the video uploader.</summary>
    [JsonPropertyName("uploader_url")]
    public string? UploaderUrl { get; set; }

    /// <summary>Full name of the channel the video is uploaded on. Note that channel fields may or may not repeat uploader fields. This depends on a particular extractor.</summary>
    [JsonPropertyName("channel")]
    public string? Channel { get; set; }

    /// <summary>Id of the channel.</summary>
    [JsonPropertyName("channel_id")]
    public string? ChannelId { get; set; }

    /// <summary>Full URL to a channel webpage.</summary>
    [JsonPropertyName("channel_url")]
    public string? ChannelUrl { get; set; }

    /// <summary>Number of followers of the channel.</summary>
    [JsonPropertyName("channel_follower_count")]
    public long? ChannelFollowerCount { get; set; }

    /// <summary>Whether the channel is verified on the platform.</summary>
    [JsonPropertyName("channel_is_verified")]
    public bool? ChannelIsVerified { get; set; }

    /// <summary>Physical location where the video was filmed.</summary>
    [JsonPropertyName("location")]
    public string? Location { get; set; }

    /// <summary>The available subtitles as a dictionary in the format {tag: subformats}. &quot;tag&quot; is usually a language code, and &quot;subformats&quot; is a list sorted from lower to higher preference, each element is a dictionary with the &quot;ext&quot; entry and one of: * &quot;data&quot;: The subtitles file contents * &quot;url&quot;: A URL pointing to the subtitles file It can optionally also have: * &quot;name&quot;: Name or description of the subtitles * &quot;http_headers&quot;: A dictionary of additional HTTP headers to add to the request. * &quot;impersonate&quot;: Impersonate target(s); same as the &quot;formats&quot; field &quot;ext&quot; will be calculated from URL if missing</summary>
    [JsonPropertyName("subtitles")]
    public Dictionary<string, SubtitleData[]>? Subtitles { get; set; }

    /// <summary>Like 'subtitles'; contains automatically generated captions instead of normal subtitles</summary>
    [JsonPropertyName("automatic_captions")]
    public Dictionary<string, SubtitleData[]>? AutomaticCaptions { get; set; }

    /// <summary>Length of the video in seconds, as an integer or float.</summary>
    [JsonPropertyName("duration")]
    public float? Duration { get; set; }

    /// <summary>How many users have watched the video on the platform.</summary>
    [JsonPropertyName("view_count")]
    public long? ViewCount { get; set; }

    /// <summary>How many users are currently watching the video on the platform.</summary>
    [JsonPropertyName("concurrent_view_count")]
    public long? ConcurrentViewCount { get; set; }

    /// <summary>Number of times the video has been saved or bookmarked</summary>
    [JsonPropertyName("save_count")]
    public long? SaveCount { get; set; }

    /// <summary>Number of positive ratings of the video</summary>
    [JsonPropertyName("like_count")]
    public long? LikeCount { get; set; }

    /// <summary>Number of negative ratings of the video</summary>
    [JsonPropertyName("dislike_count")]
    public long? DislikeCount { get; set; }

    /// <summary>Number of reposts of the video</summary>
    [JsonPropertyName("repost_count")]
    public long? RepostCount { get; set; }

    /// <summary>Average rating given by users, the scale used depends on the webpage</summary>
    [JsonPropertyName("average_rating")]
    public double? AverageRating { get; set; }

    /// <summary>Number of comments on the video</summary>
    [JsonPropertyName("comment_count")]
    public long? CommentCount { get; set; }

    /// <summary>A list of comments, each with one or more of the following properties (all but one of text or html optional):</summary>
    [JsonPropertyName("comments")]
    public CommentData[]? Comments { get; set; }

    /// <summary>Age restriction for the video, as an integer (years)</summary>
    [JsonPropertyName("age_limit")]
    public int? AgeLimit { get; set; }

    /// <summary>The URL to the video webpage, if given to yt-dlp it should allow to get the same result again. (It will be set by YoutubeDL if it's missing)</summary>
    [JsonPropertyName("webpage_url")]
    public string? WebpageUrl { get; set; }

    /// <summary>A list of categories that the video falls in, for example [&quot;Sports&quot;, &quot;Berlin&quot;]</summary>
    [JsonPropertyName("categories")]
    public string[]? Categories { get; set; }

    /// <summary>A list of tags assigned to the video, e.g. [&quot;sweden&quot;, &quot;pop music&quot;]</summary>
    [JsonPropertyName("tags")]
    public string[]? Tags { get; set; }

    /// <summary>A list of the video cast</summary>
    [JsonPropertyName("cast")]
    public string[]? Cast { get; set; }

    /// <summary>True, False, or None (=unknown). Whether this video is a live stream that goes on instead of a fixed-length video.</summary>
    [JsonPropertyName("is_live")]
    public bool? IsLive { get; set; }

    /// <summary>True, False, or None (=unknown). Whether this video was originally a live stream.</summary>
    [JsonPropertyName("was_live")]
    public bool? WasLive { get; set; }

    /// <summary>None (=unknown), 'is_live', 'is_upcoming', 'was_live', 'not_live', or 'post_live' (was live, but VOD is not yet processed) If absent, automatically set from is_live, was_live</summary>
    [JsonPropertyName("live_status")]
    public string? LiveStatus { get; set; }

    /// <summary>Time in seconds where the reproduction should start, as specified in the URL.</summary>
    [JsonPropertyName("start_time")]
    public float? StartTime { get; set; }

    /// <summary>Time in seconds where the reproduction should end, as specified in the URL.</summary>
    [JsonPropertyName("end_time")]
    public float? EndTime { get; set; }

    /// <summary>A list of dictionaries, with the following entries:</summary>
    [JsonPropertyName("chapters")]
    public ChapterData[]? Chapters { get; set; }

    /// <summary>A list of dictionaries, with the following entries:</summary>
    [JsonPropertyName("heatmap")]
    public string[]? Heatmap { get; set; }

    /// <summary>Whether this video is allowed to play in embedded players on other sites. Can be True (=always allowed), False (=never allowed), None (=unknown), or a string specifying the criteria for embedability; e.g. 'whitelist'</summary>
    [JsonPropertyName("playable_in_embed")]
    public string? PlayableInEmbed { get; set; }

    /// <summary>Under what condition the video is available. One of 'private', 'premium_only', 'subscriber_only', 'needs_auth', 'unlisted' or 'public'. Use 'InfoExtractor._availability' to set it</summary>
    [JsonPropertyName("availability")]
    public string? Availability { get; set; }

    /// <summary>The type of media as classified by the site, e.g. &quot;episode&quot;, &quot;clip&quot;, &quot;trailer&quot; _old_archive_ids: A list of old archive ids needed for backward compatibility. Use yt_dlp.utils.make_archive_id to generate ids _format_sort_fields: A list of fields to use for sorting formats __post_extractor: A function to be called just before the metadata is written to either disk, logger or console. The function must return a dict which will be added to the info_dict. This is useful for additional information that is time-consuming to extract. Note that the fields thus extracted will not be available to output template and match_filter. So, only &quot;comments&quot; and &quot;comment_count&quot; are currently allowed to be extracted via this method.</summary>
    [JsonPropertyName("media_type")]
    public string[]? MediaType { get; set; }

    /// <summary>Name or title of the chapter the video belongs to.</summary>
    [JsonPropertyName("chapter")]
    public string? Chapter { get; set; }

    /// <summary>Number of the chapter the video belongs to, as an integer.</summary>
    [JsonPropertyName("chapter_number")]
    public int? ChapterNumber { get; set; }

    /// <summary>Id of the chapter the video belongs to, as a unicode string.</summary>
    [JsonPropertyName("chapter_id")]
    public string? ChapterId { get; set; }

    /// <summary>Title of the series or programme the video episode belongs to.</summary>
    [JsonPropertyName("series")]
    public string? Series { get; set; }

    /// <summary>Id of the series or programme the video episode belongs to, as a unicode string.</summary>
    [JsonPropertyName("series_id")]
    public string? SeriesId { get; set; }

    /// <summary>Title of the season the video episode belongs to.</summary>
    [JsonPropertyName("season")]
    public string? Season { get; set; }

    /// <summary>Number of the season the video episode belongs to, as an integer.</summary>
    [JsonPropertyName("season_number")]
    public int? SeasonNumber { get; set; }

    /// <summary>Id of the season the video episode belongs to, as a unicode string.</summary>
    [JsonPropertyName("season_id")]
    public string? SeasonId { get; set; }

    /// <summary>Title of the video episode. Unlike mandatory video title field, this field should denote the exact title of the video episode without any kind of decoration.</summary>
    [JsonPropertyName("episode")]
    public string? Episode { get; set; }

    /// <summary>Number of the video episode within a season, as an integer.</summary>
    [JsonPropertyName("episode_number")]
    public int? EpisodeNumber { get; set; }

    /// <summary>Id of the video episode, as a unicode string.</summary>
    [JsonPropertyName("episode_id")]
    public string? EpisodeId { get; set; }

    /// <summary>Title of the track.</summary>
    [JsonPropertyName("track")]
    public string? Track { get; set; }

    /// <summary>Number of the track within an album or a disc, as an integer.</summary>
    [JsonPropertyName("track_number")]
    public int? TrackNumber { get; set; }

    /// <summary>Id of the track (useful in case of custom indexing, e.g. 6.iii), as a unicode string.</summary>
    [JsonPropertyName("track_id")]
    public string? TrackId { get; set; }

    /// <summary>List of artists of the track.</summary>
    [JsonPropertyName("artists")]
    public string[]? Artists { get; set; }

    /// <summary>List of composers of the piece.</summary>
    [JsonPropertyName("composers")]
    public string[]? Composers { get; set; }

    /// <summary>List of genres of the track.</summary>
    [JsonPropertyName("genres")]
    public string[]? Genres { get; set; }

    /// <summary>Title of the album the track belongs to.</summary>
    [JsonPropertyName("album")]
    public string? Album { get; set; }

    /// <summary>Type of the album (e.g. &quot;Demo&quot;, &quot;Full-length&quot;, &quot;Split&quot;, &quot;Compilation&quot;, etc).</summary>
    [JsonPropertyName("album_type")]
    public string? AlbumType { get; set; }

    /// <summary>List of all artists appeared on the album. E.g. [&quot;Ash Borer&quot;, &quot;Fell Voices&quot;] or [&quot;Various Artists&quot;]. Useful for splits and compilations.</summary>
    [JsonPropertyName("album_artists")]
    public string[]? AlbumArtists { get; set; }

    /// <summary>Number of the disc or other physical medium the track belongs to, as an integer.</summary>
    [JsonPropertyName("disc_number")]
    public int? DiscNumber { get; set; }

    /// <summary>Start time of the section in seconds</summary>
    [JsonPropertyName("section_start")]
    public long? SectionStart { get; set; }

    /// <summary>End time of the section in seconds</summary>
    [JsonPropertyName("section_end")]
    public long? SectionEnd { get; set; }

    /// <summary>Number of rows in each storyboard fragment, as an integer</summary>
    [JsonPropertyName("rows")]
    public long? Rows { get; set; }

    /// <summary>Number of columns in each storyboard fragment, as an integer</summary>
    [JsonPropertyName("columns")]
    public long? Columns { get; set; }

    /// <summary>Use &quot;composers&quot; instead. Composer(s) of the piece, comma-separated.</summary>
    [JsonPropertyName("composer")]
    public string? Composer { get; set; }

    /// <summary>Use &quot;artists&quot; instead. Artist(s) of the track, comma-separated.</summary>
    [JsonPropertyName("artist")]
    public string? Artist { get; set; }

    /// <summary>Use &quot;genres&quot; instead. Genre(s) of the track, comma-separated.</summary>
    [JsonPropertyName("genre")]
    public string? Genre { get; set; }

    /// <summary>Use &quot;album_artists&quot; instead. All artists appeared on the album, comma-separated.</summary>
    [JsonPropertyName("album_artist")]
    public string? AlbumArtist { get; set; }

    /// <summary>Use &quot;creators&quot; instead. The creator of the video. Unless mentioned otherwise, the fields should be Unicode strings. Unless mentioned otherwise, None is equivalent to absence of information. _type &quot;playlist&quot; indicates multiple videos. There must be a key &quot;entries&quot;, which is a list, an iterable, or a PagedList object, each element of which is a valid dictionary by this specification.</summary>
    [JsonPropertyName("creator")]
    public string? Creator { get; set; }

    /// <summary>The total number of videos in a playlist. If not given, YoutubeDL tries to calculate it from &quot;entries&quot; _type &quot;multi_video&quot; indicates that there are multiple videos that form a single show, for examples multiple acts of an opera or TV episode. It must have an entries key like a playlist and contain all the keys</summary>
    [JsonPropertyName("playlist_count")]
    public long? PlaylistCount { get; set; }

    /// <summary>Name of the extractor that produced this result.</summary>
    [JsonPropertyName("extractor")]
    public string? Extractor { get; set; }

    /// <summary>Key of the extractor.</summary>
    [JsonPropertyName("extractor_key")]
    public string? ExtractorKey { get; set; }

    /// <summary>Playlist entries (when ResultType is playlist).</summary>
    [JsonPropertyName("entries")]
    public VideoData[]? Entries { get; set; }

    /// <summary>Basename of the webpage URL.</summary>
    [JsonPropertyName("webpage_url_basename")]
    public string? WebpageUrlBasename { get; set; }

    /// <summary>Domain of the webpage URL.</summary>
    [JsonPropertyName("webpage_url_domain")]
    public string? WebpageUrlDomain { get; set; }

}
