// <auto-generated/>
// Source: https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/common.py
// Run YtdlpPocoGenerator to regenerate this file.

#nullable enable

using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace YtdlpPoco;

/// <summary>
/// Represents video metadata as extracted by yt-dlp.
/// See <see href="https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/common.py">yt-dlp common.py</see> for field documentation.
/// This file is auto-generated by YtdlpPocoGenerator.
/// </summary>
public class VideoData
{
    /// <summary>The result type: video, playlist, url, url_transparent, multi_video.</summary>
    [JsonPropertyName("_type")]
    public string? ResultType { get; set; }

    /// <summary>Video identifier.</summary>
    [JsonPropertyName("id")]
    public string? Id { get; set; }

    /// <summary>Video title, unescaped.</summary>
    [JsonPropertyName("title")]
    public string? Title { get; set; }

    /// <summary>A list of dictionaries for each format available, ordered from worst to best quality.</summary>
    [JsonPropertyName("formats")]
    public FormatData[]? Formats { get; set; }

    /// <summary>Final video URL.</summary>
    [JsonPropertyName("url")]
    public string? Url { get; set; }

    /// <summary>Video filename extension.</summary>
    [JsonPropertyName("ext")]
    public string? Ext { get; set; }

    /// <summary>The video format, defaults to ext (used for --get-format)</summary>
    [JsonPropertyName("format")]
    public string? Format { get; set; }

    /// <summary>SWF Player URL (used for rtmpdump).</summary>
    [JsonPropertyName("player_url")]
    public string? PlayerUrl { get; set; }

    /// <summary>True if a direct video file was given (must only be set by GenericIE)</summary>
    [JsonPropertyName("direct")]
    public string? Direct { get; set; }

    /// <summary>A secondary title of the video.</summary>
    [JsonPropertyName("alt_title")]
    public string? AltTitle { get; set; }

    /// <summary>An alternative identifier for the video, not necessarily unique, but available before title.</summary>
    [JsonPropertyName("display_id")]
    public string? DisplayId { get; set; }

    /// <summary>A list of dictionaries, with the following entries:</summary>
    [JsonPropertyName("thumbnails")]
    public ThumbnailData[]? Thumbnails { get; set; }

    /// <summary>Full URL to a video thumbnail image.</summary>
    [JsonPropertyName("thumbnail")]
    public string? Thumbnail { get; set; }

    /// <summary>Full video description.</summary>
    [JsonPropertyName("description")]
    public string? Description { get; set; }

    /// <summary>Full name of the video uploader.</summary>
    [JsonPropertyName("uploader")]
    public string? Uploader { get; set; }

    /// <summary>License name the video is licensed under.</summary>
    [JsonPropertyName("license")]
    public string? License { get; set; }

    /// <summary>List of creators of the video.</summary>
    [JsonPropertyName("creators")]
    public string[]? Creators { get; set; }

    /// <summary>UNIX timestamp of the moment the video was uploaded</summary>
    [JsonPropertyName("timestamp")]
    public long? Timestamp { get; set; }

    /// <summary>Video upload date in UTC (YYYYMMDD).</summary>
    [JsonPropertyName("upload_date")]
    public string? UploadDate { get; set; }

    /// <summary>UNIX timestamp of the moment the video was released.</summary>
    [JsonPropertyName("release_timestamp")]
    public long? ReleaseTimestamp { get; set; }

    /// <summary>The date (YYYYMMDD) when the video was released in UTC.</summary>
    [JsonPropertyName("release_date")]
    public string? ReleaseDate { get; set; }

    /// <summary>Year (YYYY) as integer when the video or album was released.</summary>
    [JsonPropertyName("release_year")]
    public int? ReleaseYear { get; set; }

    /// <summary>UNIX timestamp of the moment the video was last modified.</summary>
    [JsonPropertyName("modified_timestamp")]
    public long? ModifiedTimestamp { get; set; }

    /// <summary>The date (YYYYMMDD) when the video was last modified in UTC.</summary>
    [JsonPropertyName("modified_date")]
    public string? ModifiedDate { get; set; }

    /// <summary>Nickname or id of the video uploader.</summary>
    [JsonPropertyName("uploader_id")]
    public string? UploaderId { get; set; }

    /// <summary>Full URL to a personal webpage of the video uploader.</summary>
    [JsonPropertyName("uploader_url")]
    public string? UploaderUrl { get; set; }

    /// <summary>Full name of the channel the video is uploaded on.</summary>
    [JsonPropertyName("channel")]
    public string? Channel { get; set; }

    /// <summary>Id of the channel.</summary>
    [JsonPropertyName("channel_id")]
    public string? ChannelId { get; set; }

    /// <summary>Full URL to a channel webpage.</summary>
    [JsonPropertyName("channel_url")]
    public string? ChannelUrl { get; set; }

    /// <summary>Number of followers of the channel.</summary>
    [JsonPropertyName("channel_follower_count")]
    public long? ChannelFollowerCount { get; set; }

    /// <summary>Whether the channel is verified on the platform.</summary>
    [JsonPropertyName("channel_is_verified")]
    public bool? ChannelIsVerified { get; set; }

    /// <summary>Physical location where the video was filmed.</summary>
    [JsonPropertyName("location")]
    public string? Location { get; set; }

    /// <summary>The available subtitles as a dictionary in the format {tag: subformats}.</summary>
    [JsonPropertyName("subtitles")]
    public Dictionary<string, SubtitleData[]>? Subtitles { get; set; }

    /// <summary>Like 'subtitles'; contains automatically generated captions instead of normal subtitles</summary>
    [JsonPropertyName("automatic_captions")]
    public Dictionary<string, SubtitleData[]>? AutomaticCaptions { get; set; }

    /// <summary>Length of the video in seconds, as an integer or float.</summary>
    [JsonPropertyName("duration")]
    public long? Duration { get; set; }

    /// <summary>How many users have watched the video on the platform.</summary>
    [JsonPropertyName("view_count")]
    public long? ViewCount { get; set; }

    /// <summary>How many users are currently watching the video on the platform.</summary>
    [JsonPropertyName("concurrent_view_count")]
    public long? ConcurrentViewCount { get; set; }

    /// <summary>Number of times the video has been saved or bookmarked</summary>
    [JsonPropertyName("save_count")]
    public long? SaveCount { get; set; }

    /// <summary>Number of positive ratings of the video</summary>
    [JsonPropertyName("like_count")]
    public long? LikeCount { get; set; }

    /// <summary>Number of negative ratings of the video</summary>
    [JsonPropertyName("dislike_count")]
    public long? DislikeCount { get; set; }

    /// <summary>Number of reposts of the video</summary>
    [JsonPropertyName("repost_count")]
    public long? RepostCount { get; set; }

    /// <summary>Average rating given by users, the scale used depends on the webpage</summary>
    [JsonPropertyName("average_rating")]
    public string? AverageRating { get; set; }

    /// <summary>Number of comments on the video</summary>
    [JsonPropertyName("comment_count")]
    public long? CommentCount { get; set; }

    /// <summary>A list of comments, each with one or more of the following properties (all but one of text or html optional):</summary>
    [JsonPropertyName("comments")]
    public CommentData[]? Comments { get; set; }

    /// <summary>Age restriction for the video, as an integer (years)</summary>
    [JsonPropertyName("age_limit")]
    public long? AgeLimit { get; set; }

    /// <summary>The URL to the video webpage, if given to yt-dlp it should allow to get the same result again.</summary>
    [JsonPropertyName("webpage_url")]
    public string? WebpageUrl { get; set; }

    /// <summary>A list of categories that the video falls in, for example [&quot;Sports&quot;, &quot;Berlin&quot;]</summary>
    [JsonPropertyName("categories")]
    public string[]? Categories { get; set; }

    /// <summary>A list of tags assigned to the video, e.</summary>
    [JsonPropertyName("tags")]
    public string[]? Tags { get; set; }

    /// <summary>A list of the video cast</summary>
    [JsonPropertyName("cast")]
    public string[]? Cast { get; set; }

    /// <summary>True, False, or None (=unknown).</summary>
    [JsonPropertyName("is_live")]
    public bool? IsLive { get; set; }

    /// <summary>True, False, or None (=unknown).</summary>
    [JsonPropertyName("was_live")]
    public bool? WasLive { get; set; }

    /// <summary>None (=unknown), 'is_live', 'is_upcoming', 'was_live', 'not_live', or 'post_live' (was live, but VOD is not yet processed) If absent, automatically set from is_live, was_live</summary>
    [JsonConverter(typeof(JsonStringEnumConverter<LiveStatus>))]
    [JsonPropertyName("live_status")]
    public LiveStatus? LiveStatus { get; set; }

    /// <summary>Time in seconds where the reproduction should start, as specified in the URL.</summary>
    [JsonPropertyName("start_time")]
    public float? StartTime { get; set; }

    /// <summary>Time in seconds where the reproduction should end, as specified in the URL.</summary>
    [JsonPropertyName("end_time")]
    public float? EndTime { get; set; }

    /// <summary>A list of dictionaries, with the following entries:</summary>
    [JsonPropertyName("chapters")]
    public ChapterData[]? Chapters { get; set; }

    /// <summary>A list of dictionaries, with the following entries:</summary>
    [JsonPropertyName("heatmap")]
    public HeatmapData[]? Heatmap { get; set; }

    /// <summary>Whether this video is allowed to play in embedded players on other sites.</summary>
    [JsonPropertyName("playable_in_embed")]
    public bool? PlayableInEmbed { get; set; }

    /// <summary>Under what condition the video is available.</summary>
    [JsonConverter(typeof(JsonStringEnumConverter<Availability>))]
    [JsonPropertyName("availability")]
    public Availability? Availability { get; set; }

    /// <summary>The type of media as classified by the site, e.</summary>
    [JsonPropertyName("media_type")]
    public string? MediaType { get; set; }

    /// <summary>Name or title of the chapter the video belongs to.</summary>
    [JsonPropertyName("chapter")]
    public string? Chapter { get; set; }

    /// <summary>Number of the chapter the video belongs to, as an integer.</summary>
    [JsonPropertyName("chapter_number")]
    public long? ChapterNumber { get; set; }

    /// <summary>Id of the chapter the video belongs to, as a unicode string.</summary>
    [JsonPropertyName("chapter_id")]
    public string? ChapterId { get; set; }

    /// <summary>Title of the series or programme the video episode belongs to.</summary>
    [JsonPropertyName("series")]
    public string? Series { get; set; }

    /// <summary>Id of the series or programme the video episode belongs to, as a unicode string.</summary>
    [JsonPropertyName("series_id")]
    public string? SeriesId { get; set; }

    /// <summary>Title of the season the video episode belongs to.</summary>
    [JsonPropertyName("season")]
    public string? Season { get; set; }

    /// <summary>Number of the season the video episode belongs to, as an integer.</summary>
    [JsonPropertyName("season_number")]
    public long? SeasonNumber { get; set; }

    /// <summary>Id of the season the video episode belongs to, as a unicode string.</summary>
    [JsonPropertyName("season_id")]
    public string? SeasonId { get; set; }

    /// <summary>Title of the video episode.</summary>
    [JsonPropertyName("episode")]
    public string? Episode { get; set; }

    /// <summary>Number of the video episode within a season, as an integer.</summary>
    [JsonPropertyName("episode_number")]
    public long? EpisodeNumber { get; set; }

    /// <summary>Id of the video episode, as a unicode string.</summary>
    [JsonPropertyName("episode_id")]
    public string? EpisodeId { get; set; }

    /// <summary>Title of the track.</summary>
    [JsonPropertyName("track")]
    public string? Track { get; set; }

    /// <summary>Number of the track within an album or a disc, as an integer.</summary>
    [JsonPropertyName("track_number")]
    public long? TrackNumber { get; set; }

    /// <summary>Id of the track (useful in case of custom indexing, e.</summary>
    [JsonPropertyName("track_id")]
    public string? TrackId { get; set; }

    /// <summary>List of artists of the track.</summary>
    [JsonPropertyName("artists")]
    public string[]? Artists { get; set; }

    /// <summary>List of composers of the piece.</summary>
    [JsonPropertyName("composers")]
    public string[]? Composers { get; set; }

    /// <summary>List of genres of the track.</summary>
    [JsonPropertyName("genres")]
    public string[]? Genres { get; set; }

    /// <summary>Title of the album the track belongs to.</summary>
    [JsonPropertyName("album")]
    public string? Album { get; set; }

    /// <summary>Type of the album (e.</summary>
    [JsonPropertyName("album_type")]
    public string? AlbumType { get; set; }

    /// <summary>List of all artists appeared on the album.</summary>
    [JsonPropertyName("album_artists")]
    public string[]? AlbumArtists { get; set; }

    /// <summary>Number of the disc or other physical medium the track belongs to, as an integer.</summary>
    [JsonPropertyName("disc_number")]
    public long? DiscNumber { get; set; }

    /// <summary>Start time of the section in seconds</summary>
    [JsonPropertyName("section_start")]
    public float? SectionStart { get; set; }

    /// <summary>End time of the section in seconds The following fields should only be set for storyboards:</summary>
    [JsonPropertyName("section_end")]
    public float? SectionEnd { get; set; }

    /// <summary>Number of rows in each storyboard fragment, as an integer</summary>
    [JsonPropertyName("rows")]
    public long? Rows { get; set; }

    /// <summary>Number of columns in each storyboard fragment, as an integer The following fields are deprecated and should not be set by new code:</summary>
    [JsonPropertyName("columns")]
    public long? Columns { get; set; }

    /// <summary>Use &quot;composers&quot; instead.</summary>
    [JsonPropertyName("composer")]
    public string? Composer { get; set; }

    /// <summary>Use &quot;artists&quot; instead.</summary>
    [JsonPropertyName("artist")]
    public string? Artist { get; set; }

    /// <summary>Use &quot;genres&quot; instead.</summary>
    [JsonPropertyName("genre")]
    public string? Genre { get; set; }

    /// <summary>Use &quot;album_artists&quot; instead.</summary>
    [JsonPropertyName("album_artist")]
    public string? AlbumArtist { get; set; }

    /// <summary>Use &quot;creators&quot; instead.</summary>
    [JsonPropertyName("creator")]
    public Dictionary<string, object[]>? Creator { get; set; }

    /// <summary>The total number of videos in a playlist.</summary>
    [JsonPropertyName("playlist_count")]
    public Dictionary<string, object[]>? PlaylistCount { get; set; }

}
