using System.Text;
using System.Web;
using YtdlpPocoGenerator.Models;

namespace YtdlpPocoGenerator.Generation;

/// <summary>
/// Generates OptionSet.*.cs partial class files from parsed option definitions.
/// This is the C# equivalent of autoconvert.py's code generation logic.
/// Output matches the existing file format: BOM UTF-8, CRLF line endings.
/// </summary>
public static class OptionSetGenerator
{
    private const int Indent = 8;
    private const string IndentStr = "        "; // 8 spaces

    /// <summary>
    /// Generates all OptionSet partial class files.
    /// Returns a dictionary of filename → file content.
    /// </summary>
    public static Dictionary<string, string> GenerateAll(
        List<OptionSection> sections,
        List<OptionDefinition>? deprecatedOptions = null)
    {
        var files = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        foreach (var section in sections)
        {
            var fileName = $"OptionSet.{section.Name}.cs";
            files[fileName] = GenerateFile(section.Options, false);
        }

        if (deprecatedOptions is { Count: > 0 })
        {
            files["OptionSet.Deprecated.cs"] = GenerateFile(deprecatedOptions, true);
        }

        return files;
    }

    /// <summary>
    /// Generates a single OptionSet.*.cs file from a list of option definitions.
    /// </summary>
    private static string GenerateFile(List<OptionDefinition> options, bool deprecated)
    {
        var attrs = new List<string>();
        var props = new List<string>();

        foreach (var opt in options)
        {
            attrs.Add(BuildAttribute(opt));
            props.AddRange(BuildProperty(opt, deprecated));
        }

        // Assemble the final file using the same template as autoconvert.py
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This code was partially generated by a tool.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine("namespace YoutubeDLSharp.Options");
        sb.AppendLine("{");
        sb.AppendLine("    public partial class OptionSet");
        sb.AppendLine("    {");

        foreach (var attr in attrs)
            sb.AppendLine(attr);

        sb.AppendLine();

        foreach (var prop in props)
            sb.AppendLine(prop);

        sb.AppendLine("    }");
        sb.AppendLine("}");

        // Convert to CRLF and add BOM
        var content = sb.ToString().Replace("\r\n", "\n").Replace("\n", "\r\n");
        return content;
    }

    /// <summary>
    /// Builds a backing field declaration line.
    /// e.g.: "        private Option&lt;bool&gt; help = new Option&lt;bool&gt;("-h", "--help");"
    /// </summary>
    private static string BuildAttribute(OptionDefinition opt)
    {
        var attrName = GetAttributeName(opt.Name);
        var multiPrefix = opt.IsMulti ? "Multi" : "";
        var literalsJoined = string.Join("\", \"", opt.Literals);

        return $"{IndentStr}private {multiPrefix}Option<{opt.CSharpType}> {attrName} = new {multiPrefix}Option<{opt.CSharpType}>(\"{literalsJoined}\");";
    }

    /// <summary>
    /// Builds the XML summary, optional [Obsolete] attribute, and property declaration lines.
    /// </summary>
    private static List<string> BuildProperty(OptionDefinition opt, bool deprecated)
    {
        var lines = new List<string>();
        var attrName = GetAttributeName(opt.Name);
        var csharpType = opt.CSharpType;

        if (opt.IsMulti)
            csharpType = $"MultiValue<{csharpType}>";

        // XML doc summary
        if (opt.DescriptionLines.Count > 0)
        {
            lines.Add($"{IndentStr}/// <summary>");
            foreach (var descLine in opt.DescriptionLines)
            {
                lines.Add($"{IndentStr}/// {EscapeXml(descLine.Trim())}");
            }
            lines.Add($"{IndentStr}/// </summary>");
        }

        // [Obsolete] attribute for deprecated options
        if (deprecated && opt.DescriptionLines.Count > 0)
        {
            var obsoleteMsg = opt.DescriptionLines[0].Trim().Replace("\"", "\\\"");
            lines.Add($"{IndentStr}[Obsolete(\"{obsoleteMsg}\")]");
        }

        // Property declaration
        lines.Add($"{IndentStr}public {csharpType} {opt.Name} {{ get => {attrName}.Value; set => {attrName}.Value = value; }}");

        return lines;
    }

    /// <summary>
    /// Converts a PascalCase property name to a camelCase attribute name.
    /// Handles C# keyword collisions (e.g. "continue" → "doContinue").
    /// Equivalent to Python's get_attr_name().
    /// </summary>
    private static string GetAttributeName(string name)
    {
        var attrName = char.ToLowerInvariant(name[0]) + name[1..];

        // Workaround for attribute names matching C# keywords
        if (attrName is "continue")
            attrName = "do" + char.ToUpperInvariant(attrName[0]) + attrName[1..];

        return attrName;
    }

    /// <summary>
    /// Escapes text for XML documentation comments.
    /// </summary>
    private static string EscapeXml(string text) =>
        text.Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;")
            .Replace("'", "&#x27;");
}
