using System.Text;
using YtdlpPocoGenerator.Models;

namespace YtdlpPocoGenerator.Generation;

/// <summary>
/// Generates C# POCO class source files from parsed field definitions.
/// All output is driven by the parsed data — no hardcoded field lists.
/// </summary>
public static class PocoGenerator
{
    private const string Namespace = "YtdlpPoco";
    private const string SourceUrl = "https://github.com/yt-dlp/yt-dlp/blob/master/yt_dlp/extractor/common.py";

    /// <summary>
    /// Generates all POCO files from the top-level field definitions parsed
    /// from common.py. Fields with sub-fields produce nested class files.
    /// </summary>
    /// <param name="topLevelFields">Fields parsed from the info_dict docstring.</param>
    /// <returns>Map of filename → file content to write to disk.</returns>
    public static Dictionary<string, string> GenerateAll(List<FieldDefinition> topLevelFields)
    {
        var files = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        // Main metadata class — always VideoData.
        files["VideoData.cs"] = GenerateVideoData(topLevelFields);

        // One nested class file per field that has sub-fields.
        // Deduplicate by class name in case two fields share a name after singularization.
        var generatedClasses = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var field in topLevelFields.Where(f => f.SubFields.Count > 0))
        {
            // entries is self-referential (VideoData[]) — no separate class needed.
            if (field.Name == "entries") continue;

            var className = TypeMapper.ToNestedClassName(field.Name);
            if (!generatedClasses.Add(className)) continue;

            files[$"{className}.cs"] = GenerateNestedClass(className, field);
        }

        return files;
    }

    // ------------------------------------------------------------------
    // VideoData
    // ------------------------------------------------------------------

    private static string GenerateVideoData(List<FieldDefinition> fields)
    {
        var sb = new StringBuilder();
        WriteHeader(sb);

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Represents video metadata as extracted by yt-dlp.");
        sb.AppendLine($"/// See <see href=\"{SourceUrl}\">yt-dlp common.py</see> for field documentation.");
        sb.AppendLine("/// This file is auto-generated by YtdlpPocoGenerator.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public class VideoData");
        sb.AppendLine("{");

        // _type is added by yt-dlp at runtime and never in the docstring
        // (the leading underscore prevents it matching the field regex).
        WriteProperty(sb, "_type", "ResultType", "string?",
            "The result type: video, playlist, url, url_transparent, multi_video.");

        // Emit priority fields first for readability, then the rest in docstring order.
        var priority = new[] { "id", "title", "formats", "url", "ext", "format_id", "format" };

        foreach (var name in priority)
        {
            var f = fields.FirstOrDefault(x => x.Name == name);
            if (f is not null) WriteFieldProperty(sb, f, fields);
        }

        foreach (var f in fields)
        {
            if (Array.IndexOf(priority, f.Name) >= 0) continue;
            WriteFieldProperty(sb, f, fields);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ------------------------------------------------------------------
    // Nested classes (FormatData, ThumbnailData, ChapterData, …)
    // ------------------------------------------------------------------

    private static string GenerateNestedClass(string className, FieldDefinition parentField)
    {
        var sb = new StringBuilder();
        WriteHeader(sb);

        // Build a human-readable summary from the parent field's description.
        var summary = TruncateSummary(parentField.Description);
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// {EscapeXml(summary)}");
        sb.AppendLine("/// This file is auto-generated by YtdlpPocoGenerator.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public class {className}");
        sb.AppendLine("{");

        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var sub in parentField.SubFields)
        {
            if (seen.Add(sub.Name))
                WriteSubFieldProperty(sb, sub);
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ------------------------------------------------------------------
    // Property writers
    // ------------------------------------------------------------------

    private static void WriteFieldProperty(
        StringBuilder sb,
        FieldDefinition field,
        IReadOnlyList<FieldDefinition>? allFields = null)
    {
        var csName = ToPascalCase(field.Name);
        var csType = TypeMapper.MapType(field, allFields);
        WriteProperty(sb, field.Name, csName, csType, field.Description);
    }

    private static void WriteSubFieldProperty(StringBuilder sb, FieldDefinition sub)
    {
        var csName = ToPascalCase(sub.Name);

        // For sub-fields, use TypeMapper with the TypeHint populated.
        var csType = TypeMapper.MapType(sub);
        WriteProperty(sb, sub.Name, csName, csType, sub.Description);
    }

    private static void WriteProperty(
        StringBuilder sb,
        string jsonName,
        string csName,
        string csType,
        string summary)
    {
        if (!string.IsNullOrWhiteSpace(summary))
            sb.AppendLine($"    /// <summary>{EscapeXml(TruncateSummary(summary))}</summary>");

        sb.AppendLine($"    [JsonPropertyName(\"{jsonName}\")]");
        sb.AppendLine($"    public {csType} {csName} {{ get; set; }}");
        sb.AppendLine();
    }

    // ------------------------------------------------------------------
    // File header
    // ------------------------------------------------------------------

    private static void WriteHeader(StringBuilder sb)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Source: {SourceUrl}");
        sb.AppendLine("// Run YtdlpPocoGenerator to regenerate this file.");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine($"namespace {Namespace};");
        sb.AppendLine();
    }

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------

    private static string ToPascalCase(string snake)
    {
        if (snake == "id") return "Id";
        if (snake == "url") return "Url";
        if (snake == "ext") return "Ext";
        if (snake == "fps") return "Fps";
        if (snake == "asr") return "Asr";
        if (snake == "tbr") return "Tbr";
        if (snake == "abr") return "Abr";
        if (snake == "vbr") return "Vbr";

        return string.Concat(
            snake.Split('_')
                 .Select(p => p.Length == 0 ? "" : char.ToUpperInvariant(p[0]) + p[1..]));
    }

    private static string TruncateSummary(string text)
    {
        // Keep summaries short — stop at the first sentence boundary.
        var idx = text.IndexOf('.');
        if (idx > 0 && idx < 200) return text[..(idx + 1)].Trim();
        if (text.Length > 200) return text[..200].Trim() + "…";
        return text.Trim();
    }

    private static string EscapeXml(string text) =>
        text.Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;");
}
